apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: generator-pubsub-coverage
  labels:
    service_name: generator
    feature_name: pubsub
    slo_name: coverage
    metadata:
      env: ${ENV}
      component: all
spec:
  description: 99% of PubSub messages are acknowledged
  backend: cloud_monitoring
  method: good_bad_ratio
  exporters: []
  service_level_indicator:
    filter_good: >
      project="${PROJECT_ID}"
      metric.type="pubsub.googleapis.com/subscription/ack_message_count"
      resource.type="pubsub_subscription"
    filter_bad: >
      project="${PROJECT_ID}"
      metric.type="pubsub.googleapis.com/subscription/num_undelivered_messages"
      resource.type="pubsub_subscription"
  goal: 0.99
