---

backends:
  backends.CustomBackend: {}
  cloud_monitoring:
    project_id: ${STACKDRIVER_HOST_PROJECT_ID}
  cloud_service_monitoring:
    project_id: ${STACKDRIVER_HOST_PROJECT_ID}
  datadog:
    api_key: ${DATADOG_API_KEY}
    app_key: ${DATADOG_APP_KEY}
  prometheus:
    url: ${PROMETHEUS_URL}

exporters:
  exporters.CustomExporter: {}
error_budget_policies:
  default:
    steps:
    - name: 1h
      burn_rate_threshold: 9
      alert: true
      message_alert: Page to defend the SLO
      message_ok: Last hour on track
      window: 3600
    - name: 12h
      burn_rate_threshold: 3
      alert: true
      message_alert: Page to defend the SLO
      message_ok: Last 12 hours on track
      window: 43200
    - name: 7d
      burn_rate_threshold: 1.5
      alert: false
      message_alert: Dev team dedicates 25% of engineers to the reliability backlog
      message_ok: Last week on track
      window: 604800
    - name: 28d
      burn_rate_threshold: 1
      alert: false
      message_alert: Freeze release, unless related to reliability or security
      message_ok: Unfreeze release, per the agreed roll-out policy
      window: 2419200
  cloud_service_monitoring:
    steps:
    - name: 1d
      window: 86400
      burn_rate_threshold: 6
      alert: true
      message_alert: Page to defend the SLO
      message_ok: Last day on track

    - name: 7d
      window: 604800
      burn_rate_threshold: 1.5
      alert: false
      message_alert: Dev team dedicates 25% of engineers to the reliability backlog
      message_ok: Last week on track

    - name: 28d
      window: 2419200
      burn_rate_threshold: 1
      alert: false
      message_alert: Freeze release, unless related to reliability or security
      message_ok: Unfreeze release, per the agreed roll-out policy
