apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: dd-app-availability-slo
  labels:
    service_name: dd
    feature_name: app
    slo_name: availability-slo
    env: ${ENV}
spec:
  description: 99% of Flask app requests return a valid HTTP code
  backend: datadog
  method: query_slo
  service_level_indicator:
    slo_id: ${DATADOG_SLO_ID}
  goal: 0.99
