apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: dd-app-availability-ratio
  labels:
    service_name: dd
    feature_name: app
    slo_name: availability-ratio
    metadata:
      env: ${ENV}
spec:
  description: 99% of Flask app requests return a valid HTTP code
  backend: datadog
  method: good_bad_ratio
  exporters:
  - pubsub
  - bigquery
  - cloud_monitoring
  service_level_indicator:
    query_good: flask_app_hello_requests.count{http.path:/, http.status_code_class:2xx}
    query_valid: flask_app_hello_requests.count{http.path:/}
  goal: 0.99
