apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: dd-app-availability-sli
  labels:
    service_name: dd
    feature_name: app
    slo_name: availability-sli
    env: ${ENV}
spec:
  description: 99% of Flask app requests return a valid HTTP code
  backend: datadog
  method: query_sli
  service_level_indicator:
    query: sum:flask_app_hello_requests.count{http.path:/, http.status_code_class:2xx}.as_count()
      / sum:flask_app_hello_requests.count{http.path:/}.as_count()
  goal: 0.98
