apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: global-pubsub-coverage
  labels:
    service_name: global
    feature_name: pubsub
    slo_name: coverage
    env: ${ENV}
spec:
  description: 75% of outstanding PubSub messages are acknowledged across all projects
  backend: cloud_monitoring
  method: good_bad_ratio
  service_level_indicator:
    filter_good: >
      metric.type="pubsub.googleapis.com/subscription/ack_message_count"
      resource.type="pubsub_subscription"
    filter_bad: >
      metric.type="pubsub.googleapis.com/subscription/num_outstanding_messages"
      resource.type="pubsub_subscription"
  goal: 0.75
