apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: ob-all-latency
  labels:
    service_name: ob
    feature_name: all
    slo_name: latency
    metadata:
      env: ${ENV}
spec:
  description: 99% of Online-Boutique HTTP requests return in less than 8ms
  backend: cloud_monitoring
  method: distribution_cut
  exporters:
  - pubsub
  - bigquery
  - cloud_monitoring
  service_level_indicator:
    filter_valid: >
      project=${ONLINE_BOUTIQUE_PROJECT_ID}
      resource.label.cluster_name="demo"
      metric.type="istio.io/service/server/response_latencies"
      resource.type="k8s_container"
      metric.labels.response_code < 500
    good_below_threshold: true
    threshold_bucket: 7
  goal: 0.99
