apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: ob-adservice-latency
  labels:
    service_name: ob
    feature_name: adservice
    slo_name: latency
    metadata:
      env: ${ENV}
spec:
  description: 99% of Online-Boutique adservice HTTP requests return in less than
    8ms
  backend: cloud_service_monitoring
  method: basic
  exporters:
  - pubsub
  - bigquery
  - cloud_monitoring
  service_level_indicator:
    cluster_istio:
      project_id: ${ONLINE_BOUTIQUE_PROJECT_ID}
      location: ${ONLINE_BOUTIQUE_LOCATION}
      cluster_name: ${ONLINE_BOUTIQUE_CLUSTER_NAME}
      service_namespace: ${ONLINE_BOUTIQUE_NAMESPACE}
      service_name: adservice
    latency:
      threshold: 8
  goal: 0.99
