apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: ob-adservice-availability
  labels:
    service_name: ob
    feature_name: adservice
    slo_name: availability
    env: ${ENV}
spec:
  description: 99% of Online-Boutique adservice HTTP requests return with a valid
    HTTP code
  backend: cloud_service_monitoring
  method: basic
  service_level_indicator:
    cluster_istio:
      project_id: ${ONLINE_BOUTIQUE_PROJECT_ID}
      location: ${ONLINE_BOUTIQUE_LOCATION}
      cluster_name: ${ONLINE_BOUTIQUE_CLUSTER_NAME}
      service_namespace: ${ONLINE_BOUTIQUE_NAMESPACE}
      service_name: adservice
    availability: {}
  goal: 0.99
