apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: test-custom-slo
  labels:
    service_name: test
    feature_name: custom
    slo_name: slo
    metadata:
      env: ${ENV}
    exporters:
      class: exporters.CustomExporter
spec:
  description: 99% of blabla
  backend: backends.CustomBackend
  method: query_sli
  exporters:
  - exporters.CustomExporter
  service_level_indicator: {}
  goal: 0.99
