apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: test-custom-slo
  labels:
    service_name: test
    feature_name: custom
    slo_name: slo
    env: ${ENV}
spec:
  description: 99% of blabla
  backend: backends.CustomBackend
  method: query_sli
  service_level_indicator: {}
  goal: 0.99
