apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: gke-flask-latency-sli
  labels:
    service_name: gke
    feature_name: flask
    slo_name: latency-sli
    metadata:
      env: ${ENV}
spec:
  description: 99% of Flask app requests return in less than 250ms
  backend: prometheus
  method: query_sli
  exporters:
  - pubsub
  - bigquery
  - cloud_monitoring
  service_level_indicator:
    expression: >
      increase(
        flask_http_request_duration_seconds_bucket{app="flask-app-tutorial", path='/',
      status=~"2..",le="0.25"}[window]
      )
       / ignoring (le)
      increase(
        flask_http_request_duration_seconds_count{app="flask-app-tutorial", path='/',
      status=~"2.."}[window]
      )
  goal: 0.99
