apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: gke-flask-availability-ratio
  labels:
    service_name: gke
    feature_name: flask
    slo_name: availability-ratio
    metadata:
      env: ${ENV}
spec:
  description: 99% of Flask app requests return a good HTTP code
  backend: prometheus
  method: good_bad_ratio
  exporters: []
  service_level_indicator:
    filter_good: flask_http_request_duration_seconds_bucket{app="flask-app-tutorial",
      path='/', status=~"2.."}
    filter_valid: flask_http_request_duration_seconds_bucket{app="flask-app-tutorial",
      path='/'}
  goal: 0.99
